version: "3.8"

services:
  react-app:
    container_name: react_compose_container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env
    networks:
      - youritsoftware
    depends_on:
      - nestjs-app

  nestjs-app:
    container_name: nestjs_compose_container
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env.development.local
    volumes:
      - ./backend:/app
    depends_on:
      - postgres

  postgres:
    container_name: postgres_compose_container
    image: postgres:latest
    env_file:
      - ./backend/.env.development.local
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: {}

networks:
  youritsoftware:
    external: false
